version: '3'
services: 
    gitlab: 
        image: 'twang2218/gitlab-ce-zh'
        hostname: 'gitlab.ljs.com'
        environment: 
          TZ: 'Asia/Shanghai'
          GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://gitlab.ljs.com:9999'
            gitlab_rails['gitlab_shell_ssh_port'] = 2222
            unicorn['port'] = 8888
            nginx['listen_port'] = 9999
            gitlab_rails['gitlab_email_enabled'] = true
            gitlab_rails['gitlab_email_from'] = '邮箱地址'
            gitlab_rails['gitlab_email_display_name'] = 'Gitlba发件时的发件人的显示名称'
            gitlab_rails['smtp_enable'] = true
            gitlab_rails['smtp_address'] = "smtp.qq.com"
            gitlab_rails['smtp_port'] = 465
            gitlab_rails['smtp_user_name'] = "邮箱地址"
            gitlab_rails['smtp_password'] = "邮箱授权码"
            gitlab_rails['smtp_domain'] = "qq.com"
            gitlab_rails['smtp_authentication'] = "login"
            gitlab_rails['smtp_enable_starttls_auto'] = true
            gitlab_rails['smtp_tls'] = true
        ports: 
          - '9999:9999'
          - '8443:443'
          - '2222:22'
        volumes:
          - $HOME/mydocker/myvolumes/gitlabfile/config:/etc/gitlab
          - $HOME/mydocker/myvolumes/gitlabfile/data:/var/opt/gitlab
          - $HOME/mydocker/myvolumes/gitlabfile/logs:/var/log/gitlab
          